=== BarshaDstudent/ElixirAngel-project/catalog_19030785.dtd
<!--Author:Barsha Kumari Das
 Date:2021-04-25
 DTD stand for document type definition.DTD is define the valid building blocks of the XML document.it 
 define the structure of the XML document.The datatype of the all the element, attributes mention in this file. PCDATA stand for parse character data. +sign stand for those element which repeate more than one times. ?sign stand for those element which may occure or maynot occure.
 IMPLIED is used for those attributes which maybe occure or maynot come.
 REQUIRED is used for the attributes those most have to occure.  
 -->
<!ELEMENT smoothMusicStore (storeDetails)>
<!ELEMENT storeDetails (storeName, websiteAddress, address, telephoneNo+,logo, music)>
<!ELEMENT storeName (#PCDATA)>
<!ELEMENT websiteAddress (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT telephoneNo (#PCDATA)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT music (div+)>
<!ELEMENT div (h1+, songs+)>
<!ELEMENT h1 (#PCDATA)>
<!ELEMENT songs (director, musician, lyricsWriter, producer+,producer1+, songName, album, durationTime, releaseDate, genre, singers+, review?, h2+, div1+, click+ )>
<!ELEMENT director (#PCDATA)>
<!ELEMENT musician (#PCDATA)>
<!ELEMENT lyricsWriter (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT producer1 (#PCDATA)>
<!ELEMENT songName (#PCDATA)>
<!ELEMENT album (#PCDATA)> <!-- parsed character data-->
<!ELEMENT durationTime (#PCDATA)>
<!ELEMENT releaseDate (year, month?, day?)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT singers (singerName+, saddress?, phone+, totalSongRecorded+, fanFollowing?)>
<!ELEMENT singerName (#PCDATA)>
<!ELEMENT saddress (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT totalSongRecorded (#PCDATA)>
<!ELEMENT fanFollowing (#PCDATA)>
<!ELEMENT review (#PCDATA)>
<!ELEMENT h2 (#PCDATA)>
<!ELEMENT div1 (#PCDATA)>
<!ELEMENT click (#PCDATA)>

<!ATTLIST div class CDATA #REQUIRED>
<!ATTLIST songs song_code CDATA #REQUIRED>
<!ATTLIST songs discNumber CDATA #IMPLIED>
<!ATTLIST songs trackNumber CDATA #IMPLIED>
<!ATTLIST musician musicianType (guitarist|drummer|Pianist|Flutist|Tubaist) #REQUIRED>
<!ATTLIST phone type (primary|secondary) #IMPLIED>
<!ATTLIST div1 cls (icon|icon2|icon3|icon4|icon5) #REQUIRED>

=== BarshaDstudent/ElixirAngel-project/catalog_19030785.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_19030785.css"?>
<!--This is the xml document for the smoothmusical store -->

<!--<smoothMusicStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
	xsi:noNamespaceSchemaLocation="catalog_19030785.xsd">-->
	<!-- the main screen of the xml file opened for example the screen that appears first when the document is opened-->
<!DOCTYPE smoothMusicStore SYSTEM "catalog_19030785.dtd">
<smoothMusicStore>
	<!--storeDetails display all the information about the store.store address, website address, telephone no and the contact no of the store is multiple-->
	<storeDetails>
		<storeName>ElixirAngel Music Store</storeName>
	    <websiteAddress>www.baniya.com</websiteAddress>
	    <address>New Baneshwor,Kathmandu</address>
	    <telephoneNo>TelephoneNo:90342312</telephoneNo>
	    <telephoneNo>PhoneNo:00342312</telephoneNo>
	    <logo></logo>
	    <music>
	    	<!--pricing-box1 is used to make the table for the details of the Jazz music and all the contain display inside the table.-->
	        <div class="pricing-box1">
	        	<!-- This h1 tag is for representing the Collection of the particular type of songs -->
	    		<h1>Jazz Music Collection</h1>
	    		<!--Inside song all the details of the song is display. song have three attributes and other element which give the proper information of about the song. the datatype of the attributes is ID, NMTOKEN, Pattern-->
		        <songs song_code="c01" discNumber="211-ED-9a" trackNumber="AE:32:ER">
			        <director>Director:Ahmad Jamal</director>
			        <!-- musician have there musiciantype attributes which repesent the type of the musician inside the songs and datatype is string-->
			        <musician musicianType="guitarist">Musician:Gil Evans,Balk James</musician>
			        <lyricsWriter>LyricsWritter:Miles Davis</lyricsWriter>
			        <producer>Producers Name:</producer>
			        <producer1>Bill Eva</producer1>
			        <producer1>Teo Macero</producer1>
			        <producer1>John Coltrane</producer1>
			        <songName>SongName:So What</songName>
			        <album>Album:Kind of blue</album>
			        <durationTime>Duration Time:9:30</durationTime>
			        <releaseDate>
				        <year>ReleaseDate:1959</year>
				        <month>August</month>
				        <day>17</day>
			        </releaseDate>
			        <genre>Genre:Jazz Music</genre>
			        <!--singers provide the details about the singer.phone element have two attributes which is primary or secondary-->
			        <singers>
				        <singerName>SingerName:Ed sheeran</singerName>
				        <saddress>Address:Framlingham, United kingdom</saddress>
				        <phone type="primary">Primary PhoneNo:0024354</phone>
				        <totalSongRecorded>TotalSongRecorded:150</totalSongRecorded>
				        <fanFollowing>FanFollowing:24M</fanFollowing>
			        </singers>
			        <review>
			        	This is good in music.The lyrics of this song is very heart touching.Many peope like this song and this song get many view and the meaning of the song is very beautiful and make the soul peaceful.
			        </review>        
			        <h2>Image of So What</h2>
			        <!--This icon for displaying the images of the songs-->
			        <div1 cls="icon"></div1>
			         <!--This click tag display more information about the songs.-->
			        <click>Click Here For More </click>   
		        </songs>    
		    </div>
            <!--pricing-box2 is used to make the table for the details of the Rock music and all the contain display inside the table.-->
		    <div class="pricing-box2">
	    		<h1>Rock Music Collection</h1>
		        <songs song_code="c02" discNumber="281-BD-2a">
			        <director>Director:Roger Mayer</director>
			        <!-- musician have there musiciantype attributes which repesent the type of the musician inside the songs-->
			        <musician musicianType="drummer">Musician:Mitch Mitchel,Jhoni Durba</musician> 
			        <lyricsWriter>LyricsWritter:Pritiam Jimi</lyricsWriter>
			        <producer>Producers Name:</producer>
			        <producer1>Bunji Garlin</producer1>
			        <producer1>Jeff Kush</producer1>
			        <producer1>Charly Jorden</producer1>
			        <songName>SongName:Purple Haze</songName>
			        <album>Album:De Lane series</album>
			        <durationTime>DurationTime:2:40</durationTime>
			        <!--Release date display the time of releasing of the song and month and day is not compulsory-->
			        <releaseDate>
				        <year>ReleaseDate:1967</year>
				        <month>March</month>
				        <day>12</day>
			        </releaseDate>
			        <genre>Gener:Rock Music</genre>
			        <!--singers provide the details about the singer.phone element have two attributes which is primary or secondary-->
			        <singers>
				        <singerName>SingerName:Jimi Hendrix</singerName>
				        <saddress>Address:Califonia, United kingdom</saddress>
				        <phone type="primary">Primary PhoneNo:1024354</phone>
				        <totalSongRecorded>TotalSongRecorded:150</totalSongRecorded>
			        </singers>
			        <review>This song is good with lyrics.The songâ€™s sound being powerfully mystifying, a search of musical spirituality.It was about going through,through this land.This mythical because that's what I like to do is write a lot of mythical scenes.You know, like the history of the wars on Neptune.</review>         
			        <h2>Image of Purple Haze</h2>
			        <!--This icon2 for displaying the images of the songs-->
			        <div1 cls="icon2"></div1>
			        <!--This click tag display more information about the songs.-->
			        <click>Click Here For More</click>   
		        </songs>    
		    </div>

            <!--pricing-box3 is used to make the table for the details of the pop music and all the contain display inside the table.-->
		    <div class="pricing-box3">
	    		<h1>Country Music Collection</h1>
		        <songs song_code="c03"  trackNumber="AE:12:ER">
			        <director>Director:Trey Parker</director>
			        <!-- musician have there musiciantype attributes which repesent the type of the musician inside the songs-->
			        <musician musicianType="Pianist">Musician:Vince Gill,Jasmin Ali</musician>
			        <lyricsWriter>LyricsWriter:Alan Jackson</lyricsWriter>
			        <producer>ProducersName:</producer>
			        <producer1>Mitch Mitchel</producer1>
                    <producer1>Noel Redding</producer1>
                    <producer1>Chandler</producer1>
			        <songName>SongName:Where were you</songName>
			        <album>Album:Drive</album>
			        <durationTime>DurationTime:5:05</durationTime>
			        <!--Release date display the time of releasing of the song and month and day is not compulsory-->
			        <releaseDate>
				        <year>ReleaseDate:2001</year>
				        <month>November</month>
				        <day>12</day>
			        </releaseDate>
			        <genre>Gener:CountryMusic</genre>
			        <!--singers provide the details about the singer.phone element have two attributes which is primary or secondary-->
			        <singers>
				        <singerName>SingerName:Alan Jackson</singerName>
				        <saddress>Address:Texas, United kingdom</saddress>
				        <phone type="primary">Primary PhoneNo:1024354</phone>
				        <phone type="secondary">Secondary PhoneNo:1064354</phone>
				        <totalSongRecorded>TotalSongRecorded:150</totalSongRecorded>
				        <fanFollowing>FanFollowing:30M</fanFollowing>
			        </singers>
			        <review>This song is good. This song touched the heart of the people. This song is written on the reaction to the spetember 11 attack in the United State, written in the form of question. Jackson desired to write a song capturing the emotion surrounding the attacks. This song recived largely positive reviews from the crities, who appreciated its sipmle largly apolitical stance. </review>         
			        <h2>Image of Country Music</h2>
			        <!--This icon3 for displaying the images of the songs-->
			        <div1 cls="icon3"></div1>
			        <!--This click tag display more information about the songs.-->
			        <click>Click Here For More</click>   
		        </songs>    
		    </div>
            <!--pricing-box4 is used to make the table for the details of the country music and all the contain display inside the table.-->
		    <div class="pricing-box4">
	    		<h1>Pop Music Collection</h1>
		        <songs song_code="c04" discNumber="281-CD-4b" trackNumber="AE:12:RR">
			        <director>DirectorName:Peggy Lipton</director>
			        <!-- musician have there musiciantype attributes which repesent the type of the musician inside the songs-->
			        <musician musicianType="Flutist">Musician:Jack Jhone,Niche Michal</musician>
			        <lyricsWriter>LyricsWritter:Rod Temperton</lyricsWriter>
			        <producer>ProducersName:</producer>
			        <producer1>Vince Gill</producer1>
			        <producer1>Stephen Erlewin</producer1>
			        <producer1>Hank William</producer1>
			        <songName>SongName:Thriller</songName>
			        <album>Album:Westlake</album>
			        <durationTime>DurationTime:5:03</durationTime>
			        <!--Release date display the time of releasing of the song and month and day is not compulsory-->
			        <releaseDate>
				        <year>ReleaseDate:1983</year>   
			        </releaseDate>
			        <genre>Genre:PopMusic</genre>
			        <!--singers provide the details about the singer.phone element have two attributes which is primary or secondary-->
			        <singers>
				        <singerName>SingerName:Michael Jackson</singerName>
				        <saddress>Address:United kingdom</saddress>
